### ISSUE TITLE
Doesn't work with custom internal DNS names

### ISSUE THREAD

**Issue by vide** [HariSekhon/nagios-plugin-kafka#2]
Hello, I'm trying to run the `nagios-plugin-check-kafka` docker image against a Kafka with an internal-only custom DNS name (basically  a `.whatever` TLD) and looks like your program is way too much opinionated about DNS names, because it complains with

```
usage: invalid host:port 'kafka-1.beta.eu-west-1.whatever:9092' defined: host
               portion 'kafka-1.beta.eu-west-1.whatever' is not a valid hostname
               or IP address
```

If I pass the IP, by default it times out with

```
UNKNOWN: self timed out after 10 secs
```

because I'm obviously using an internal DNS server and dockerd doesn't know anything about it. [1]

If I pass the `--dns my-dns-server` flag to `docker run` then it works as expected with the broker IP but still complains with the first error message when passing the DNS name. 

[1] and since kafka redirects clients to the brokers FQDNs, resolution goes wrong and hence the timeout

**Comment by HariSekhon** [comment]
The DNS validation is extendable and documented in the underlying library's readme, here:

https://github.com/HariSekhon/lib-java#custom-tlds

Just edit that file in lib/src/main/resources/custom_tlds.txt and rebuild a new jar via `make`.

Docker source is in the [Dockerfiles](https://github.com/HariSekhon/Dockerfiles) repo if you want to see how to build a new docker image.

**Comment by vide** [comment]
Oh, didn't clone the repo with the submodules so I missed it. 
In the end to make our own docker image I've just started from your official one and overwritten the fat jar. It works nicely. Thanks for your project!
